### PR TITLE
Fix the parsing of empty values

### PR DESCRIPTION
**Pull request by drewag**
Addresses https://github.com/Zewo/Zewo/issues/86

### CODE REVIEW

**Comment by paulofaria** [comment]
@drewag Thanks a lot man! Can you add some tests? I set up travis yesterday! Finally we can start testing! 😊

**Comment by drewag** [comment]
Ya sure, I actually attempted to initially but accidentally had the test file in the wrong folder and couldn't figure out why the tests weren't running. I'm new to the Swift test suite but I think I figured it out :). Let me know if I need to make any changes.

**Comment by paulofaria** [comment]
Beautiful!

**Comment by paulofaria** [comment]
@drewag Are you on our Slack? [slack.zewo.io](slack.zewo.io)

**Comment by drewag** [comment]
I am now :)

**Pull request merged**
